version: '3'
services:
  signaler:
    build: ./
    env_file: .env
    links:
      - redis
      - kafka
  tracker:
    image: msull92/macd-tracker
    env_file: tracker.env
  redis:
    image: redis
  kafka:
    image: spotify/kafka
    environment:
      - ADVERTISED_PORT=9092
      - ADVERTISED_HOST=kafka
